apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-unyq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-unyq
    app.kubernetes.io/part-of: ci1t-43256-0008-app
  name: devfile-sample-unyq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-unyq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-unyq
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0008-tenant/ci1t-43256-0008-app/devfile-sample-unyq@sha256:ae09bdda5f254b9a6d1c146810645a5863a64664c3a8851ac6dc9a795f958c29
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
